// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/app/_middleware.ts";
import * as $4 from "./routes/app/dashboard.tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/login.tsx";
import * as $8 from "./routes/register.tsx";
import * as $$0 from "./islands/Banner.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/form/Button.tsx";
import * as $$3 from "./islands/form/Select.tsx";
import * as $$4 from "./islands/form/TextField.tsx";
import * as $$5 from "./islands/routes/register/UserTypeInput.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/app/_middleware.ts": $3,
    "./routes/app/dashboard.tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/login.tsx": $7,
    "./routes/register.tsx": $8,
  },
  islands: {
    "./islands/Banner.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/form/Button.tsx": $$2,
    "./islands/form/Select.tsx": $$3,
    "./islands/form/TextField.tsx": $$4,
    "./islands/routes/register/UserTypeInput.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
