// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(app)/_layout.tsx";
import * as $1 from "./routes/(app)/_middleware.ts";
import * as $2 from "./routes/(app)/api/channel/[id].ts";
import * as $3 from "./routes/(app)/api/channel/index.ts";
import * as $4 from "./routes/(app)/api/join/[code].ts";
import * as $5 from "./routes/(app)/dashboard.tsx";
import * as $6 from "./routes/(app)/logout.ts";
import * as $7 from "./routes/_404.tsx";
import * as $8 from "./routes/_app.tsx";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/login.tsx";
import * as $11 from "./routes/register.tsx";
import * as $$0 from "./islands/Banner.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/app/dashboard/ChannelList.tsx";
import * as $$3 from "./islands/app/dashboard/JoinChannelForm.tsx";
import * as $$4 from "./islands/form/Button.tsx";
import * as $$5 from "./islands/form/Checkbox.tsx";
import * as $$6 from "./islands/form/ModalForm.tsx";
import * as $$7 from "./islands/form/Select.tsx";
import * as $$8 from "./islands/form/TextField.tsx";
import * as $$9 from "./islands/register/UserTypeInput.tsx";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $0,
    "./routes/(app)/_middleware.ts": $1,
    "./routes/(app)/api/channel/[id].ts": $2,
    "./routes/(app)/api/channel/index.ts": $3,
    "./routes/(app)/api/join/[code].ts": $4,
    "./routes/(app)/dashboard.tsx": $5,
    "./routes/(app)/logout.ts": $6,
    "./routes/_404.tsx": $7,
    "./routes/_app.tsx": $8,
    "./routes/index.tsx": $9,
    "./routes/login.tsx": $10,
    "./routes/register.tsx": $11,
  },
  islands: {
    "./islands/Banner.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/app/dashboard/ChannelList.tsx": $$2,
    "./islands/app/dashboard/JoinChannelForm.tsx": $$3,
    "./islands/form/Button.tsx": $$4,
    "./islands/form/Checkbox.tsx": $$5,
    "./islands/form/ModalForm.tsx": $$6,
    "./islands/form/Select.tsx": $$7,
    "./islands/form/TextField.tsx": $$8,
    "./islands/register/UserTypeInput.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
