// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(app)/_layout.tsx";
import * as $1 from "./routes/(app)/_middleware.ts";
import * as $2 from "./routes/(app)/api/channel/[id].ts";
import * as $3 from "./routes/(app)/api/channel/[id]/index.ts";
import * as $4 from "./routes/(app)/api/channel/[id]/join-requests.ts";
import * as $5 from "./routes/(app)/api/channel/[id]/text-message.ts";
import * as $6 from "./routes/(app)/api/channel/index.ts";
import * as $7 from "./routes/(app)/api/join/confirm.ts";
import * as $8 from "./routes/(app)/api/join/decline.ts";
import * as $9 from "./routes/(app)/api/join/request.ts";
import * as $10 from "./routes/(app)/channel/[id].tsx";
import * as $11 from "./routes/(app)/dashboard.tsx";
import * as $12 from "./routes/(app)/logout.ts";
import * as $13 from "./routes/_404.tsx";
import * as $14 from "./routes/_app.tsx";
import * as $15 from "./routes/index.tsx";
import * as $16 from "./routes/login.tsx";
import * as $17 from "./routes/register.tsx";
import * as $$0 from "./islands/Banner.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Dropdown.tsx";
import * as $$3 from "./islands/app/channel/[id]/JoinRequestsDropdown.tsx";
import * as $$4 from "./islands/app/dashboard/ChannelList.tsx";
import * as $$5 from "./islands/app/dashboard/JoinChannelForm.tsx";
import * as $$6 from "./islands/form/Button.tsx";
import * as $$7 from "./islands/form/Checkbox.tsx";
import * as $$8 from "./islands/form/ErrorMessage.tsx";
import * as $$9 from "./islands/form/ModalForm.tsx";
import * as $$10 from "./islands/form/Select.tsx";
import * as $$11 from "./islands/form/TextField.tsx";
import * as $$12 from "./islands/register/UserTypeInput.tsx";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $0,
    "./routes/(app)/_middleware.ts": $1,
    "./routes/(app)/api/channel/[id].ts": $2,
    "./routes/(app)/api/channel/[id]/index.ts": $3,
    "./routes/(app)/api/channel/[id]/join-requests.ts": $4,
    "./routes/(app)/api/channel/[id]/text-message.ts": $5,
    "./routes/(app)/api/channel/index.ts": $6,
    "./routes/(app)/api/join/confirm.ts": $7,
    "./routes/(app)/api/join/decline.ts": $8,
    "./routes/(app)/api/join/request.ts": $9,
    "./routes/(app)/channel/[id].tsx": $10,
    "./routes/(app)/dashboard.tsx": $11,
    "./routes/(app)/logout.ts": $12,
    "./routes/_404.tsx": $13,
    "./routes/_app.tsx": $14,
    "./routes/index.tsx": $15,
    "./routes/login.tsx": $16,
    "./routes/register.tsx": $17,
  },
  islands: {
    "./islands/Banner.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Dropdown.tsx": $$2,
    "./islands/app/channel/[id]/JoinRequestsDropdown.tsx": $$3,
    "./islands/app/dashboard/ChannelList.tsx": $$4,
    "./islands/app/dashboard/JoinChannelForm.tsx": $$5,
    "./islands/form/Button.tsx": $$6,
    "./islands/form/Checkbox.tsx": $$7,
    "./islands/form/ErrorMessage.tsx": $$8,
    "./islands/form/ModalForm.tsx": $$9,
    "./islands/form/Select.tsx": $$10,
    "./islands/form/TextField.tsx": $$11,
    "./islands/register/UserTypeInput.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
